Homework 1
unters/java-course-tinkoff pull request #1
Opened 2023-10-05 15:23 UTC by unters

Solutions to tasks from homework 1.

2023-10-07 20:14 UTC, SHvatov requested changes
в целом все хорошо, пара минорных замечаний по коду

2023-10-07 20:14 UTC, SHvatov commented on src/main/java/edu/hw1/Task2.java
> +        int valueCopy = value;
можно просто классическое `temp`)

2023-10-07 20:14 UTC, SHvatov commented on src/main/java/edu/hw1/Task4.java
> +
лишняя пустая строка

2023-10-07 20:14 UTC, SHvatov commented on src/main/java/edu/hw1/Task5.java
> +    /* Let's assume that we can build descendant value only for string with even size.  */
к чему этот комментарий? на вход подается инт, а в комменте речь идет про строку)

2023-10-07 20:14 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        /* value must be strictly greater than 1000.  */
по условию число 4-х значное, если в тесте проставить 10_000, то он падает с `java.lang.StackOverflowError`

2023-10-07 20:14 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +    private final static long K = 6174;
название можно сделать чуть более очевидным

2023-10-07 20:14 UTC, SHvatov commented on src/main/java/edu/hw1/Task7.java
> +    public static int rotateLeft(int n, int shift) {
вот в этом методе очень помогли бы комментарии) в остальном 🔥

2023-10-07 20:14 UTC, SHvatov commented on src/test/java/edu/hw1/Task1Test.java
> +    @Test void minutesToSeconds_InputContainsZeroOrMoreThanOneDelimiter_ReturnMinusOne() {
аннотации должны быть сверху, так как они имеют тенденцию плодиться. еще советую посмотреть в сторону использования [параметризированных тестов](https://www.baeldung.com/parameterized-tests-junit-5)

2023-10-08 14:30 UTC, unters commented on src/main/java/edu/hw1/Task1.java
> +    public static BigInteger minutesToSeconds(String s) {
По условию задачи количество минут никак не ограничено сверху, поэтому я воспользовался `BigInteger`. Ясно, что никакая мыслимая видеозапись даже отдаленно не может иметь длительность в $9 * 10^{18}$ минут (что в соответствии с сегодняшней научной картиной мира было бы на несколько порядков больше, чем возраст Вселенной), но тем не менее я воспринял условие задачи буквально - без ограничения сверху, значит без ограничения сверху (в следующей редакции домашнего задания `BigInteger` будет заменен на `long`).

2023-10-08 15:01 UTC, unters commented on src/main/java/edu/hw1/Task6.java
> +        /* value must be strictly greater than 1000.  */
Внезапно, `StackOverflowError` будет выбрасываться даже на некоторых четырехзначных числах, например, на числе $9998$:
1. $9998 - 8999 = 999$,
2. $999 - 999 = 0$ (и далее бесконечный цикл).

Как выяснилось в ходе обсуждения заданий в беседе курса, на каждой очередной итерации алгоритма Капрекара при выполнении арифметических операций следует сохранять нули. Тогда для числа $9998$:
1. $9998 - 8999 = 0999$,
2. $9990 - 0999 = 8991$,
3. $9981 - 1899 = 8082$,
4. $8820 - 0288 = 8532$,
5. $8532 - 2358 = 6174$ (постоянная Капрекара).

Также можно заметить, что если сохранять нули, вычисления приведут к постоянной Капрекара даже для $1000$ (в условии задания входное число должно быть строго больше $1000$):
1. $1000 - 0001 = 0999$,
2. $9990 - 0999 = 8991$,
3. $9981 - 1899 = 8082$,
4. $8820 - 0288 = 8532$,
5. $8532 - 2358 = 6174$ (постоянная Капрекара).

2023-10-08 17:04 UTC, unters commented on src/main/java/edu/hw1/Task1.java
> +    public static BigInteger minutesToSeconds(String s) {
При наименовании методов и параметров я руководствовался формулировками в домашних заданиях, в частности, в задании 1 в примерах искомый метод называется `minutesToSeconds()`. В последующей редакции домашнего задания он будет называться `convertTimestampToSeconds(String timestamp)`.

2023-10-08 18:08 UTC, unters commented on src/test/java/edu/hw1/Task1Test.java
> +    @Test void minutesToSeconds_InputContainsZeroOrMoreThanOneDelimiter_ReturnMinusOne() {
Изначально я писал каждую аннотацию на отдельной строке, однако при форматировании кода (<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>L</kbd>) они переносились на строку, на которой были объявлены соответствующие аннотациям функции - я подумал, что это связано с checkstyle'ом. Когда я сел исправлять домашнее задание, такое поведение при форматировании кода больше не наблюдалось :/

2023-10-08 18:41 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +    public static BigInteger minutesToSeconds(String s) {
ИМХО, в самом задании наименование не самое лучше и по смыслу не очень подходит - все-таки конвертируем минуты и секунды в секунды. Новое название мне по душе :)

2023-10-08 18:44 UTC, SHvatov commented on src/main/java/edu/hw1/Task1.java
> +    public static BigInteger minutesToSeconds(String s) {
Не знал, что наша вселенная такая молодая :)

Понятно, но, как я написал в комменте, `Big***` классы используются при необходимости точных вычислений, а в большинстве кейсов достаточно и примитивов. Но не при работе с деньгами ;)

2023-10-08 18:45 UTC, SHvatov commented on src/main/java/edu/hw1/Task6.java
> +        /* value must be strictly greater than 1000.  */
Очень интересные наблюдения!

2023-10-08 18:46 UTC, SHvatov commented on src/test/java/edu/hw1/Task1Test.java
> +    @Test void minutesToSeconds_InputContainsZeroOrMoreThanOneDelimiter_ReturnMinusOne() {
Бывает :)

2023-10-08 18:47 UTC, SHvatov commented on src/main/java/edu/hw1/Task2.java
>      @SuppressWarnings("MagicNumber")
Все еще суппресситься MagicNumber. Это из-за 10? Давай унесем литерал в константу.

2023-10-08 18:51 UTC, SHvatov commented
@unters поправь, пожалуйста, `@SuppressWarnings("MagicNumber")`, и мы в расчете :)

2023-10-08 18:51 UTC, SHvatov approved these changes

2023-10-08 19:00 UTC, unters commented
> @unters поправь, пожалуйста, `@SuppressWarnings("MagicNumber")`, и мы в расчете :)

Готово.

2023-10-08 19:04 UTC, unters commented on src/main/java/edu/hw1/Task2.java
>      @SuppressWarnings("MagicNumber")
Изменил - вынес в `private static final int BASE`.

2023-10-08 19:05 UTC, merged